In [1]:
#import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"C:\Users\puji\forestfires.csv")

In [3]:
df

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
5    8  6   aug  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.00
6    8  6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.00
7    8  6   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.00
8    8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.00
9    7  5   sep  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.00
10   7  5   sep  sat  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.00
11   7  5   sep  sat  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0   0.00
12   6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.00
13   6  5   sep  mon  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0   0.00
14   6  5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.00
15   6  5   sep  fri  93.3  141.2  713.9  13.9  22.9  44   5.4   0.0   0.00
16   5  5   mar  sat  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0   0.00
17   8  5   oct  mon  84.9   32.8  664.2   3.0  16.7  47   4.9   0.0   0.00
18   6  4   mar  wed  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.00
19   6  4   apr  sat  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   0.00
20   6  4   sep  tue  91.0  129.5  692.6   7.0  18.3  40   2.7   0.0   0.00
21   5  4   sep  mon  91.8   78.5  724.3   9.2  19.1  38   2.7   0.0   0.00
22   7  4   jun  sun  94.3   96.3  200.0  56.1  21.0  44   4.5   0.0   0.00
23   7  4   aug  sat  90.2  110.9  537.4   6.2  19.5  43   5.8   0.0   0.00
24   7  4   aug  sat  93.5  139.4  594.2  20.3  23.7  32   5.8   0.0   0.00
25   7  4   aug  sun  91.4  142.4  601.4  10.6  16.3  60   5.4   0.0   0.00
26   7  4   sep  fri  92.4  117.9  668.0  12.2  19.0  34   5.8   0.0   0.00
27   7  4   sep  mon  90.9  126.5  686.5   7.0  19.4  48   1.3   0.0   0.00
28   6  3   sep  sat  93.4  145.4  721.4   8.1  30.2  24   2.7   0.0   0.00
29   6  3   sep  sun  93.5  149.3  728.6   8.1  22.8  39   3.6   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
487  5  4   aug  tue  95.1  141.3  605.8  17.7  26.4  34   3.6   0.0  16.40
488  4  4   aug  tue  95.1  141.3  605.8  17.7  19.4  71   7.6   0.0  46.70
489  4  4   aug  wed  95.1  141.3  605.8  17.7  20.6  58   1.3   0.0   0.00
490  4  4   aug  wed  95.1  141.3  605.8  17.7  28.7  33   4.0   0.0   0.00
491  4  4   aug  thu  95.8  152.0  624.1  13.8  32.4  21   4.5   0.0   0.00
492  1  3   aug  fri  95.9  158.0  633.6  11.3  32.4  27   2.2   0.0   0.00
493  1  3   aug  fri  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0  43.32
494  6  6   aug  sat  96.0  164.0  643.0  14.0  30.8  30   4.9   0.0   8.59
495  6  6   aug  mon  96.2  175.5  661.8  16.8  23.9  42   2.2   0.0   0.00
496  4  5   aug  mon  96.2  175.5  661.8  16.8  32.6  26   3.1   0.0   2.77
497  3  4   aug  tue  96.1  181.1  671.2  14.3  32.3  27   2.2   0.0  14.68
498  6  5   aug  tue  96.1  181.1  671.2  14.3  33.3  26   2.7   0.0  40.54
499  7  5   aug  tue  96.1  181.1  671.2  14.3  27.3  63   4.9   6.4  10.82
500  8  6   aug  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
501  7  5   aug  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
502  4  4   aug  tue  96.1  181.1  671.2  14.3  20.7  69   4.9   0.4   0.00
503  2  4   aug  wed  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0   1.95
504  4  3   aug  wed  94.5  139.4  689.1  20.0  28.9  29   4.9   0.0  49.59
505  1  2   aug  thu  91.0  163.2  744.4  10.1  26.7  35   1.8   0.0   5.80
506  1  2   aug  fri  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0   0.00
507  2  4   aug  fri  91.0  166.9  752.6   7.1  25.9 

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df.isnull().any()

X        False
Y        False
month    False
day      False
FFMC     False
DMC      False
DC       False
ISI      False
temp     False
RH       False
wind     False
rain     False
area     False
dtype: bool

In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
df.drop(["month"],axis=1,inplace=True)

In [8]:
df.drop(["day"],axis=1,inplace=True)

In [9]:
df

X  Y  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
5    8  6  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.00
6    8  6  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.00
7    8  6  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.00
8    8  6  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.00
9    7  5  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.00
10   7  5  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.00
11   7  5  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0   0.00
12   6  5  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.00
13   6  5  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0   0.00
14   6  5  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.00
15   6  5  93.3  141.2  713.9  13.9  22.9  44   5.4   0.0   0.00
16   5  5  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0   0.00
17   8  5  84.9   32.8  664.2   3.0  16.7  47   4.9   0.0   0.00
18   6  4  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.00
19   6  4  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   0.00
20   6  4  91.0  129.5  692.6   7.0  18.3  40   2.7   0.0   0.00
21   5  4  91.8   78.5  724.3   9.2  19.1  38   2.7   0.0   0.00
22   7  4  94.3   96.3  200.0  56.1  21.0  44   4.5   0.0   0.00
23   7  4  90.2  110.9  537.4   6.2  19.5  43   5.8   0.0   0.00
24   7  4  93.5  139.4  594.2  20.3  23.7  32   5.8   0.0   0.00
25   7  4  91.4  142.4  601.4  10.6  16.3  60   5.4   0.0   0.00
26   7  4  92.4  117.9  668.0  12.2  19.0  34   5.8   0.0   0.00
27   7  4  90.9  126.5  686.5   7.0  19.4  48   1.3   0.0   0.00
28   6  3  93.4  145.4  721.4   8.1  30.2  24   2.7   0.0   0.00
29   6  3  93.5  149.3  728.6   8.1  22.8  39   3.6   0.0   0.00
..  .. ..   ...    ...    ...   ...   ...  ..   ...   ...    ...
487  5  4  95.1  141.3  605.8  17.7  26.4  34   3.6   0.0  16.40
488  4  4  95.1  141.3  605.8  17.7  19.4  71   7.6   0.0  46.70
489  4  4  95.1  141.3  605.8  17.7  20.6  58   1.3   0.0   0.00
490  4  4  95.1  141.3  605.8  17.7  28.7  33   4.0   0.0   0.00
491  4  4  95.8  152.0  624.1  13.8  32.4  21   4.5   0.0   0.00
492  1  3  95.9  158.0  633.6  11.3  32.4  27   2.2   0.0   0.00
493  1  3  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0  43.32
494  6  6  96.0  164.0  643.0  14.0  30.8  30   4.9   0.0   8.59
495  6  6  96.2  175.5  661.8  16.8  23.9  42   2.2   0.0   0.00
496  4  5  96.2  175.5  661.8  16.8  32.6  26   3.1   0.0   2.77
497  3  4  96.1  181.1  671.2  14.3  32.3  27   2.2   0.0  14.68
498  6  5  96.1  181.1  671.2  14.3  33.3  26   2.7   0.0  40.54
499  7  5  96.1  181.1  671.2  14.3  27.3  63   4.9   6.4  10.82
500  8  6  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
501  7  5  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
502  4  4  96.1  181.1  671.2  14.3  20.7  69   4.9   0.4   0.00
503  2  4  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0   1.95
504  4  3  94.5  139.4  689.1  20.0  28.9  29   4.9   0.0  49.59
505  1  2  91.0  163.2  744.4  10.1  26.7  35   1.8   0.0   5.80
506  1  2  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0   0.00
507  2  4  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
508  1  2  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
509  5  4  91.0  166.9  752.6   7.1  21.1  71   7.6   1.4   2.17
510  6  5  91.0  166.9  752.6   7.1  18.2  62   5.4   0.0   0.43
511  8  6  81.6   56.7  665.6   1.9  27.8  35   2.7   0.0   0.00
512  4  3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3  79.5    3.0  106.7   1.1  11.

In [10]:
X = df.iloc[:, :-1].values
y = df.iloc[:, 10].values

In [11]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X, y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [12]:
y_pred=regressor.predict([[7,5,86.2,26.2,94.3,5.1,8.2,51,6.7,0]])

In [13]:
y_pred

array([5.049])

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [16]:
X_train

array([[ 7. ,  3. , 90.6, ..., 27. ,  4. ,  0. ],
       [ 8. ,  6. , 84.9, ..., 32. ,  4. ,  0. ],
       [ 6. ,  3. , 93.4, ..., 24. ,  2.7,  0. ],
       ...,
       [ 6. ,  5. , 92.8, ..., 27. ,  2.2,  0. ],
       [ 6. ,  5. , 53.4, ..., 90. ,  2.7,  0. ],
       [ 8. ,  3. , 88.2, ..., 79. ,  4. ,  0. ]])

In [17]:
X_test

array([[ 1. ,  4. , 91.5, ..., 35. ,  2.2,  0. ],
       [ 1. ,  2. , 91.4, ..., 39. ,  6.3,  0. ],
       [ 4. ,  4. , 93.5, ..., 39. ,  4.9,  0. ],
       ...,
       [ 2. ,  4. , 63.5, ..., 38. ,  3.6,  0. ],
       [ 4. ,  4. , 95.8, ..., 21. ,  4.5,  0. ],
       [ 2. ,  4. , 93.6, ..., 66. ,  4.9,  0. ]])

In [18]:
y_train

array([0.00000e+00, 5.44000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       9.27000e+00, 1.39900e+01, 2.13000e+00, 6.57000e+00, 1.09300e+01,
       1.30500e+01, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       2.12880e+02, 5.39000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       1.76000e+00, 0.00000e+00, 0.00000e+00, 9.00000e-01, 0.00000e+00,
       1.90000e+00, 1.92300e+01, 4.70000e-01, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 7.60000e-01, 1.63000e+00, 0.00000e+00, 5.65000e+00,
       0.00000e+00, 0.00000e+00, 7.03200e+01, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 3.43600e+01, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       1.03390e+02, 2.42400e+01, 0.00000e+00, 7.13000e+01, 8.68000e+00,
       3.35000e+00, 0.00000e+00, 0.00000e+00, 2.18000e+00, 0.00000e+00,
       0.00000e+00, 6.58000e+00, 2.47700e+01, 0.00000e+00, 9.96000e+00,
       3.07000e+00, 7.48000e+00, 0.00000e+00, 1.11900e+01, 4.40000e+00,
       0.00000e+00, 0.00000e+00, 7.04000e+00, 1.52000e+00, 1.430

In [19]:
y_test

array([2.819e+01, 0.000e+00, 4.855e+01, 2.100e-01, 0.000e+00, 1.008e+01,
       0.000e+00, 6.100e-01, 0.000e+00, 0.000e+00, 0.000e+00, 2.210e+00,
       2.140e+00, 7.400e+00, 0.000e+00, 7.076e+01, 2.341e+01, 0.000e+00,
       6.800e-01, 1.116e+01, 0.000e+00, 2.470e+00, 0.000e+00, 1.120e+00,
       5.400e-01, 1.600e+01, 4.950e+00, 1.106e+01, 0.000e+00, 7.730e+00,
       1.001e+01, 0.000e+00, 0.000e+00, 1.264e+01, 9.518e+01, 0.000e+00,
       1.002e+01, 3.702e+01, 0.000e+00, 0.000e+00, 0.000e+00, 3.520e+00,
       0.000e+00, 3.300e+00, 2.030e+00, 0.000e+00, 0.000e+00, 2.600e+01,
       1.940e+00, 0.000e+00, 1.106e+01, 0.000e+00, 8.160e+00, 0.000e+00,
       3.940e+00, 1.950e+00, 0.000e+00, 2.140e+00, 2.613e+01, 5.800e+00,
       2.530e+00, 0.000e+00, 0.000e+00, 0.000e+00, 6.380e+00, 4.610e+00,
       8.849e+01, 0.000e+00, 0.000e+00, 0.000e+00, 2.003e+01, 8.020e+00,
       0.000e+00, 0.000e+00, 1.564e+01, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 7.300e+00, 5.200e-01, 

In [20]:
X_train.shape

(413, 10)

In [21]:
y_pred=regressor.predict(X_test)

In [22]:
y_pred

array([1.98380000e+01, 2.23280000e+01, 2.05010000e+01, 3.93000000e-01,
       3.63400000e+00, 8.76600000e+00, 0.00000000e+00, 1.48200000e+01,
       1.55666667e+00, 0.00000000e+00, 0.00000000e+00, 1.62600000e+00,
       2.57600000e+00, 5.18000000e+00, 0.00000000e+00, 5.15110000e+01,
       1.27580000e+01, 0.00000000e+00, 5.42400000e+00, 1.43570000e+01,
       1.05100000e+00, 2.15400000e+00, 1.13200000e+00, 6.17000000e+00,
       1.73000000e+00, 1.33800000e+01, 2.69100000e+00, 2.10180000e+01,
       2.42400000e+00, 1.12410000e+01, 8.55766667e+00, 6.37400000e+00,
       0.00000000e+00, 1.02840000e+01, 7.44240000e+01, 7.46500000e+00,
       6.08400000e+00, 2.75470000e+01, 0.00000000e+00, 4.66600000e+00,
       5.36000000e-01, 3.28500000e+00, 5.73200000e+00, 2.73500000e+00,
       1.96800000e+00, 2.20510000e+01, 2.71500000e+00, 2.05790000e+01,
       5.34900000e+00, 8.59000000e+00, 9.06000000e+00, 4.11700000e+00,
       1.09570000e+01, 0.00000000e+00, 2.63600000e+00, 6.14100000e+00,
      

In [23]:
from sklearn.metrics import r2_score

In [24]:
r2_score(y_test,y_pred)

0.7391417088869211